### PR TITLE
Misc fixes, including timing

### PR DESCRIPTION
**Pull request by stromnet**
Hi,

I've now successfully built the DS2423 device and got it working on a Mega88A with 8MHz crystal.
I've made some minor fixes to the build system, which I *think* are correct?

There was also some timing issues, the OWT_LOWTIME was too high, search failed with DS2480B (but worked with LinkUSB; see commit for more details).
Which master have you used?

Johan

### CODE REVIEW

**Comment by stromnet** [comment]
For the record; some timings:

```
Master: DS2480B
Slave: OWT_LOWTIME T_(50)-2

First bit in search; master read:
	1.47 uS  low-edge and int0-dbg (enter)
	10.9uS low-edge and int0-dbg (exit)
	(line high)
	10.3uS  low-edge and high-edge (device write-1)
	58.7uS low-edge and OWT_LOWTIME timer dbg-enter
	65.3uS low-edge and OWT_LOWTIME timer dbg-exit
	67.1 uS timer exit and start of next slot (low-edge)

	66.7uS  low-edge and next low-edge

Second bit in search; master-read:
	4.17 uS low-edge and int0-dbg-enter
	13.7 uS low-edge and int0-dbg-exit
	(line pulled low)
	61.7us low-edge and OWT_LOWTIME timer dbg-enter
	66.1uS low-edge and line release (Barely visible; timeslot is over!)
	68.1uS low-edge and OWT_LOWTIME timer dbg-exit

	67.3 uS  low-edge and next low-edge

<SLOT MISSED, THIRD BIT READ IS DONE 1 SLOT TOO LATE>

Third bit in search; master-write-decision:
	2.9 uS low-edge and int0-dbg-enter
	11.7uS low-edge and int0-dbg-exit
	39.5us low-edge and OWT_READLINE timer dbg-enter (sample 1)
	48.1us low-edge and OWT_READLINE timer dbg-exit

	67.3 us low-edge and next low-edge


Tested without debug pin, 1w looked same.
```
```
Master: DS2480B
Slave: OWT_LOWTIME T_(40)-2

First bit in search; master read:
	2.9uS  low-edge and int0-dbg (enter)
	11.9uS low-edge and int0-dbg (exit)
	(line high)
	11.9uS  low-edge and high-edge (device write-1)
	51.5uS low-edge and OWT_LOWTIME timer dbg-enter
	58.3uS low-edge and OWT_LOWTIME timer dbg-exit
	8.1 uS timer exit and start of next slot (low-edge)

	67uS  low-edge and next low-edge

Second bit in search; master-read:
	2.1uS low-edge and int0-dbg-enter
	11.5uS low-edge and int0-dbg-exit
	(line pulled low)
	52.1us low-edge and OWT_LOWTIME timer dbg-enter
	56.7uS low-edge and line release
	58.1uS low-edge and OWT_LOWTIME timer dbg-exit

	67uS  low-edge and next low-edge


Third bit in search; master-write-decision:
	2.9uS low-edge and int0-dbg-enter
	11.9uS low-edge and int0-dbg-exit
	40.5us low-edge and OWT_READLINE timer dbg-enter (sample 1)
	47.9us low-edge and OWT_READLINE timer dbg-exit

	67.1 us low-edge and next low-edge

```
```
Master:LinkUSB
Slave: OWT_LOWTIME T_(50)-2

First bit in search; master read:
	3.6 uS  low-edge and int0-dbg (enter)
	12.2 uS low-edge and int0-dbg (exit)
	(line high)
	9.0uS  low-edge and high-edge (device write-1)
	60.2uS low-edge and OWT_LOWTIME timer dbg-enter
	67.4uS low-edge and OWT_LOWTIME timer dbg-exit
	
	80.4uS  low-edge and next low-edge

Second bit in search; master-read:
	2.02 uS low-edge and int0-dbg-enter
	11.0 uS low-edge and int0-dbg-exit
	(line pulled low)
	59.2us low-edge and OWT_LOWTIME timer dbg-enter
	63.4uS low-edge and line release
	66.8uS low-edge and OWT_LOWTIME timer dbg-exit

	89.2 uS  low-edge and next low-edge

Third bit in search; master-write-decision:
	3.42uS low-edge and int0-dbg-enter
	12.2uS low-edge and int0-dbg-exit
	41us low-edge and OWT_READLINE timer dbg-enter (sample 1)
	48.2us low-edge and OWT_READLINE timer dbg-exit

	83 us low-edge and next low-edge

```

**Comment by smurfix** [comment]
Thanks! Merged.

NB: I moved to m-o-a-t/owslave as upstream repository.

On 26.05.2015 22:39, Johan Ström wrote:
>
> For the record; some timings:
>
> |Master: DS2480B
> Slave: OWT_LOWTIME T_(50)-2
>
> First bit in search; master read:
>     1.47 uS  low-edge and int0-dbg (enter)
>     10.9uS low-edge and int0-dbg (exit)
>     (line high)
>     10.3uS  low-edge and high-edge (device write-1)
>     58.7uS low-edge and OWT_LOWTIME timer dbg-enter
>     65.3uS low-edge and OWT_LOWTIME timer dbg-exit
>     67.1 uS timer exit and start of next slot (low-edge)
>
>     66.7uS  low-edge and next low-edge
>
> Second bit in search; master-read:
>     4.17 uS low-edge and int0-dbg-enter
>     13.7 uS low-edge and int0-dbg-exit
>     (line pulled low)
>     61.7us low-edge and OWT_LOWTIME timer dbg-enter
>     66.1uS low-edge and line release (Barely visible; timeslot is over!)
>     68.1uS low-edge and OWT_LOWTIME timer dbg-exit
>
>     67.3 uS  low-edge and next low-edge
>
> <SLOT MISSED, THIRD BIT READ IS DONE 1 SLOT TOO LATE>
>
> Third bit in search; master-write-decision:
>     2.9 uS low-edge and int0-dbg-enter
>     11.7uS low-edge and int0-dbg-exit
>     39.5us low-edge and OWT_READLINE timer dbg-enter (sample 1)
>     48.1us low-edge and OWT_READLINE timer dbg-exit
>
>     67.3 us low-edge and next low-edge
>
>
> Tested without debug pin, 1w looked same.
> |
> |Master: DS2480B
> Slave: OWT_LOWTIME T_(40)-2
>
> First bit in search; master read:
>     2.9uS  low-edge and int0-dbg (enter)
>     11.9uS low-edge and int0-dbg (exit)
>     (line high)
>     11.9uS  low-edge and high-edge (device write-1)
>     51.5uS low-edge and OWT_LOWTIME timer dbg-enter
>     58.3uS low-edge and OWT_LOWTIME timer dbg-exit
>     8.1 uS timer exit and start of next slot (low-edge)
>
>     67uS  low-edge and next low-edge
>
> Second bit in search; master-read:
>     2.1uS low-edge and int0-dbg-enter
>     11.5uS low-edge and int0-dbg-exit
>     (line pulled low)
>     52.1us low-edge and OWT_LOWTIME timer dbg-enter
>     56.7uS low-edge and line release
>     58.1uS low-edge and OWT_LOWTIME timer dbg-exit
>
>     67uS  low-edge and next low-edge
>
>
> Third bit in search; master-write-decision:
>     2.9uS low-edge and int0-dbg-enter
>     11.9uS low-edge and int0-dbg-exit
>     40.5us low-edge and OWT_READLINE timer dbg-enter (sample 1)
>     47.9us low-edge and OWT_READLINE timer dbg-exit
>
>     67.1 us low-edge and next low-edge
>
> |
> |Master:LinkUSB
> Slave: OWT_LOWTIME T_(50)-2
>
> First bit in search; master read:
>     3.6 uS  low-edge and int0-dbg (enter)
>     12.2 uS low-edge and int0-dbg (exit)
>     (line high)
>     9.0uS  low-edge and high-edge (device write-1)
>     60.2uS low-edge and OWT_LOWTIME timer dbg-enter
>     67.4uS low-edge and OWT_LOWTIME timer dbg-exit
>
>     80.4uS  low-edge and next low-edge
>
> Second bit in search; master-read:
>     2.02 uS low-edge and int0-dbg-enter
>     11.0 uS low-edge and int0-dbg-exit
>     (line pulled low)
>     59.2us low-edge and OWT_LOWTIME timer dbg-enter
>     63.4uS low-edge and line release
>     66.8uS low-edge and OWT_LOWTIME timer dbg-exit
>
>     89.2 uS  low-edge and next low-edge
>
> Third bit in search; master-write-decision:
>     3.42uS low-edge and int0-dbg-enter
>     12.2uS low-edge and int0-dbg-exit
>     41us low-edge and OWT_READLINE timer dbg-enter (sample 1)
>     48.2us low-edge and OWT_READLINE timer dbg-exit
>
>     83 us low-edge and next low-edge
>
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smurfix/owslave/pull/9#issuecomment-105658448>.
>


-- 
-- Matthias Urlichs

**Comment by stromnet** [comment]
Doh, my bad. I've changed my upstreams to m-o-a-t but for some reason I picked this repo when doing the pull request.

Thanks for merge!
Have you made any measurements on 8MHz internal RC? From the data-sheet, it should run at approx 8Mhz at 3V. At 5.0V it is slightly faster, I think, which could make the old values work better.

**Comment by smurfix** [comment]
On 27.05.2015 07:58, Johan Ström wrote:
> Have you made any measurements on 8MHz internal RC? From the
> data-sheet, it should run at approx 8Mhz at 3V. At 5.0V it is slightly
> faster, I think, which could make the old values work better. 
Not yet; I'll test on my hardware later this week, too much else to do
at the moment :-/

I'm doing 8MHz at 5V due to sheer laziness on my part (don't want to
bother soldering the external crystal if I can avoid it).

-- 
-- Matthias Urlichs

**Comment by stromnet** [comment]
Did some additional testing, with internal 8MHz @ 5V, resulting in some thoughts on changing the timings:

```
Reset pulse (clean restarted slave):

1.2uS falling-edge to int-enter  (OWM_SLEEP)
10.2uS edge to int-exit
422uS edge to timer-min-reset enter
442uS edge to timer-min-reset exit
510uS falling-edge to rising-edge
53uS rising-edge to OWT_RESET_PRESENCE-timer
56.4uS rising-edge to our falling edge (presence pulse)
166uS, falling edge to rising edge (lenght of our presence pulse; OWT_PRESENCE)
```
Seems legit!

In a non-first-transaction test I also see a DBG pulse 40uS after first low edge, which I guess is a OWT_READLINE, followed by a reset-sense-pulse at 436us after low edge. Then it continues as above after the rising edge.

Looking at the search-bit-pattern:
```
read-slot-1 (slave writes 1)
  2.6us after low edge, int enter
  11us after low edge, int exit
  52.4uS after low edge, write1-timer-enter
  58.8us after low edge, write1-timer-exit

read-slot-2 (slave writes 0)
  2.8us after low edge, int enter
  11us after low edge, int exit
  (line brought low)
  51.2uS after low edge, write0-timer-enter
  55.2 us after low edge, line released
  58.6us after low edge, write0-timer-exit

master-write-slot-3 (slave reads)
  2us after low edge, int enter
  12.2us after low edge, int exit
  40uS after low edge, sample-timer-enter
  47.8us after low edge, sample-timer-exit
```

I'd say thats pretty much the same as with the 8MHz crystal, and within limits.

But, OWT_LOWTIME might be a bit high, leaving the ISR 58uS after initial low edge. Given a slot width of 60uS, with >5uS recovery time (1), this gives us ~7uS margin until the next slot. The master should sample somewhere around 11-15uS after low-edge (2), so 58uS is quite high. 
In comparison, a DS18B20 keeps the line low for 27.4uS during the search.

With `LOWTIME (T_(40)-2)`, the line is kept low for 58uS (above)
With `LOWTIME (T_(30)-2)`, the line is kept low for 43uS.
With `LOWTIME (T_(25)-2)`, the line is kept low for 39uS.
With `LOWTIME (T_(20)-2)`, the line is kept low for 35uS.

The device is found fine in either of the above, in my test bench. I'm not sure how much a more complex network would impact, but 35uS seems quite sufficient, compared to the others? The main upside with a lower timeout is for parasite powered devices in the net, with maximized pull-up time.

What are your previous experience from tweaking the timings?

--

1) according to DS2406 spec; cannot find a PDF with the "definitive" answer? The DS2480B does not have any spec on recovery time.. 

2) The DS2480B spec specifies Standard sampling at 8+3uS = 11uS. The DS2406 pdf says "The optimal sampling point for the master is as close as possible to the end time of the 15μs tRDV period without exceeding tRDV. For the case of a Read-one time slot, this maximizes the amount of time for the pull-up resistor to recover the line to a high level. For a Read-zero time slot it ensures that a read will occur before the fastest 1-Wire devices(s) release the line (tRELEASE = 0)."

**Comment by smurfix** [comment]
On 27.05.2015 21:58, Johan Ström wrote:
>
> Did some additional testing, with internal 8MHz @ 5V, resulting in
> some thoughts on changing the timings:
>
Thanks for the additional tests. One point of note may be that if you
have long and possibly high-impedance wires, you get longer signal rise
times, ringing and signal reflections, and other not-so-cute artefacts,
all of which may adversely affect the timing.

That being said, I'll experiment with dynamically setting the signal
timing parameters once I have part of my new network set up.

Now if somebody would write code for doing firmware updates across
1wire, that'd be really awesome …

-- 
-- Matthias Urlichs

**Comment by stromnet** [comment]
Indeed. Unfortunately I won't be able to measure my full 1w-net, 80m or so with 25+ devices. But I'll try to setup a test-bed with some long wires and see if I can get any interesting results.

Theoretically, what kind of impact would a shorter LOWTIME have on a long/high-impedance network? A *too long* one (while writing 0) would mean that the bus might not recover back up until the next timeslot begins, but with a too short one, what is to be expected?

Regarding writing flash from running code, interesting point, and would rock to have it, but probably a bit over my head, my AVR experience is somewhat limited :)

**Comment by stromnet** [comment]
Forgot to comment here.. But for the record, I've been testing out on a long roll of cable with successful results. The exact length isn't really known, but scoping the falling edge on the master end and the slave end gave ~1.47uS. CAT5 propagation delay according to wikipedia is 4.8-5.3nS/m, which gives ~270-300m, which sounds reasonable.
With Mega88 powered through the bus (internal 8Mhz), using three ground wires, this worked perfectly fine with few or zero CRC16 errors. With some additional DS18B20's on the bus, it still seemed to work fine but with some more CRC16 errors, could be due to bad connections though, kind of crappy setup..

No guarantee that it works as good in a real net with more devices, but positive results none the less!

Experimented with LOWTIME _T value between 20 and 40 without any apparent issues. Timings looked good on the scope regardless.

During testing I've used my old DSO. Kind of messy to watch longer stretches of signals (more than a few hundred bits) on it though, so I got a Logic 8 from Saleae; **extremely** nice piece of HW to use during slave debugging! More or less unlimited storage length, well worth the money for my hobby use!

**Pull request merged**
